import { ConvexError } from "convex/values";

/** Stable codes for expected failures — UI maps these to copy in packages/app. */
export const AppErrorCode = {
  UNAUTHORIZED: "UNAUTHORIZED",
  TASK_TITLE_REQUIRED: "TASK_TITLE_REQUIRED",
  TASK_NOT_FOUND: "TASK_NOT_FOUND",
  PUSH_TOKEN_INVALID: "PUSH_TOKEN_INVALID",
  EMAIL_SEND_FAILED: "EMAIL_SEND_FAILED",
  ADMIN_FORBIDDEN: "ADMIN_FORBIDDEN",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  INSTITUTION_NOT_FOUND: "INSTITUTION_NOT_FOUND",
  RUN_NOT_FOUND: "RUN_NOT_FOUND",
  RUN_TRANSITION_INVALID: "RUN_TRANSITION_INVALID",
  RUN_NOT_AT_GATE: "RUN_NOT_AT_GATE",
  SOURCE_DOC_NOT_FOUND: "SOURCE_DOC_NOT_FOUND",
  OBJECT_STORE_NOT_CONFIGURED: "OBJECT_STORE_NOT_CONFIGURED",
  GATE_ITEMS_UNRESOLVED: "GATE_ITEMS_UNRESOLVED",
  REVIEW_ITEM_NOT_FOUND: "REVIEW_ITEM_NOT_FOUND",
  REVIEW_ITEM_ALREADY_RESOLVED: "REVIEW_ITEM_ALREADY_RESOLVED",
  REVIEW_ITEM_SOURCE_REQUIRED: "REVIEW_ITEM_SOURCE_REQUIRED",
  COURSE_NOT_FOUND: "COURSE_NOT_FOUND",
  QUESTION_NOT_FOUND: "QUESTION_NOT_FOUND",
  QUESTION_INVALID: "QUESTION_INVALID",
  UNITS_REQUIRED: "UNITS_REQUIRED",
  UNITS_BLOCKED: "UNITS_BLOCKED",
  TTS_NOT_CONFIGURED: "TTS_NOT_CONFIGURED",
  NARRATION_NOT_FOUND: "NARRATION_NOT_FOUND",
  NARRATION_EDIT_BREAKS_CARD: "NARRATION_EDIT_BREAKS_CARD",
  RUN_NOT_EDITABLE: "RUN_NOT_EDITABLE",
  COURSE_PUBLISHED: "COURSE_PUBLISHED",
  PUBLISH_VERSION_CONFLICT: "PUBLISH_VERSION_CONFLICT",
} as const;

export type AppErrorCodeType = (typeof AppErrorCode)[keyof typeof AppErrorCode];

export type AppErrorPayload = { code: AppErrorCodeType };

/** Throw a structured app error the client maps to human-readable copy. */
export function appError(code: AppErrorCodeType): never {
  throw new ConvexError({ code } satisfies AppErrorPayload);
}
