import { ConvexError } from "convex/values";

/** Stable codes for expected failures — product packages map these to UI copy. */
export const AppErrorCode = {
  UNAUTHORIZED: "UNAUTHORIZED",
  TASK_TITLE_REQUIRED: "TASK_TITLE_REQUIRED",
  TASK_NOT_FOUND: "TASK_NOT_FOUND",
  PUSH_TOKEN_INVALID: "PUSH_TOKEN_INVALID",
  EMAIL_SEND_FAILED: "EMAIL_SEND_FAILED",
  ADMIN_FORBIDDEN: "ADMIN_FORBIDDEN",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  INSTITUTION_NOT_FOUND: "INSTITUTION_NOT_FOUND",
  INSTITUTION_NAME_REQUIRED: "INSTITUTION_NAME_REQUIRED",
  INSTITUTION_ALREADY_EXISTS: "INSTITUTION_ALREADY_EXISTS",
  INSTITUTION_WEBSITE_URL_INVALID: "INSTITUTION_WEBSITE_URL_INVALID",
  INSTITUTION_WEBSITE_URL_REQUIRED: "INSTITUTION_WEBSITE_URL_REQUIRED",
  INSTITUTION_THEME_EXTRACTION_FAILED: "INSTITUTION_THEME_EXTRACTION_FAILED",
  INSTITUTION_LOGO_URL_INVALID: "INSTITUTION_LOGO_URL_INVALID",
  INSTITUTION_LOGO_FETCH_FAILED: "INSTITUTION_LOGO_FETCH_FAILED",
  INSTITUTION_LOGO_FILE_INVALID: "INSTITUTION_LOGO_FILE_INVALID",
  INSTITUTION_LOGO_NOT_FOUND: "INSTITUTION_LOGO_NOT_FOUND",
  RUN_NOT_FOUND: "RUN_NOT_FOUND",
  RUN_TRANSITION_INVALID: "RUN_TRANSITION_INVALID",
  RUN_NOT_AT_GATE: "RUN_NOT_AT_GATE",
  RUN_ASSET_SELECTION_INVALID: "RUN_ASSET_SELECTION_INVALID",
  RUN_SELECTED_ASSETS_NOT_CLEARED: "RUN_SELECTED_ASSETS_NOT_CLEARED",
  SOURCE_DOC_NOT_FOUND: "SOURCE_DOC_NOT_FOUND",
  SOURCE_DOCS_REQUIRED: "SOURCE_DOCS_REQUIRED",
  SOURCE_DOC_FACTS_PENDING_REVIEW: "SOURCE_DOC_FACTS_PENDING_REVIEW",
  OBJECT_STORE_NOT_CONFIGURED: "OBJECT_STORE_NOT_CONFIGURED",
  COURSE_NOT_FOUND: "COURSE_NOT_FOUND",
  COURSE_TITLE_REQUIRED: "COURSE_TITLE_REQUIRED",
  MODULE_NOT_FOUND: "MODULE_NOT_FOUND",
  MODULE_TITLE_REQUIRED: "MODULE_TITLE_REQUIRED",
  QUESTION_NOT_FOUND: "QUESTION_NOT_FOUND",
  QUESTION_INVALID: "QUESTION_INVALID",
  UNITS_REQUIRED: "UNITS_REQUIRED",
  UNITS_BLOCKED: "UNITS_BLOCKED",
  TTS_NOT_CONFIGURED: "TTS_NOT_CONFIGURED",
  TTS_VOICE_INVALID: "TTS_VOICE_INVALID",
  TTS_AUDITION_FAILED: "TTS_AUDITION_FAILED",
  NARRATION_NOT_FOUND: "NARRATION_NOT_FOUND",
  NARRATION_EDIT_BREAKS_CARD: "NARRATION_EDIT_BREAKS_CARD",
  CARD_NOT_FOUND: "CARD_NOT_FOUND",
  CARD_PROPS_INVALID: "CARD_PROPS_INVALID",
  CARD_ENTER_AT_WORD_INVALID: "CARD_ENTER_AT_WORD_INVALID",
  RUN_NOT_EDITABLE: "RUN_NOT_EDITABLE",
  COURSE_PUBLISHED: "COURSE_PUBLISHED",
  PUBLISH_VERSION_CONFLICT: "PUBLISH_VERSION_CONFLICT",
  ASSET_KEY_INVALID: "ASSET_KEY_INVALID",
  ASSET_JOB_NOT_FOUND: "ASSET_JOB_NOT_FOUND",
  ASSET_NOT_FOUND: "ASSET_NOT_FOUND",
  ASSET_NOT_CLEARED: "ASSET_NOT_CLEARED",
  ASSET_KIND_MISMATCH: "ASSET_KIND_MISMATCH",
  CONVERTER_NOT_CONFIGURED: "CONVERTER_NOT_CONFIGURED",
  OUTLINE_NOT_FOUND: "OUTLINE_NOT_FOUND",
  OUTLINE_INVALID: "OUTLINE_INVALID",
  MODEL_ROUTING_INVALID: "MODEL_ROUTING_INVALID",
  RENDERER_NOT_CONFIGURED: "RENDERER_NOT_CONFIGURED",
  RENDER_JOB_NOT_FOUND: "RENDER_JOB_NOT_FOUND",
  RENDER_JOB_NOT_RETRYABLE: "RENDER_JOB_NOT_RETRYABLE",
  AVATAR_NOT_CONFIGURED: "AVATAR_NOT_CONFIGURED",
  AVATAR_LOOK_INVALID: "AVATAR_LOOK_INVALID",
  AVATAR_GENERATION_FAILED: "AVATAR_GENERATION_FAILED",
} as const;

export type AppErrorCodeType = (typeof AppErrorCode)[keyof typeof AppErrorCode];

export type AppErrorPayload = { code: AppErrorCodeType };

/** Throw a structured app error the client maps to human-readable copy. */
export function appError(code: AppErrorCodeType): never {
  throw new ConvexError({ code } satisfies AppErrorPayload);
}
